[versions]
kotlin = "2.1.0"
develocity = "3.19.1"
junit = "5.10.0"
picnic = "0.7.0"
ktor-client-cio = "3.0.3"
publishing = "1.2.1"
ktlint = "12.1.2"
gson = "2.10.1"


[libraries]
develocity = { group = "com.gradle", name = "develocity-gradle-plugin", version.ref = "develocity"}
junit = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
picnic = { group = "com.jakewharton.picnic", name = "picnic", version.ref = "picnic" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor-client-cio" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "publishing" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
